"""Add audit_log advanced columns

Revision ID: ae0a2e6f4adc
Revises: g4b7c2d1e805
Create Date: 2026-09-21 21:40:28.245186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0a2e6f4adc'
down_revision: Union[str, Sequence[str], None] = 'g4b7c2d1e805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('event_category', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('audit_log', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.alter_column('m_directorio_metrica', 'codigo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('m_directorio_metrica', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('uq_directorio_metrica_codigo'), table_name='m_directorio_metrica')
    op.create_unique_constraint(None, 'm_directorio_metrica', ['codigo'])
    op.drop_column('medicos_normativos', 'res_anestesiologo_fecha_venc')
    op.drop_column('medicos_normativos', 'res_ejercicio_fecha_venc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos_normativos', sa.Column('res_ejercicio_fecha_venc', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('medicos_normativos', sa.Column('res_anestesiologo_fecha_venc', sa.DATE(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'm_directorio_metrica', type_='unique')
    op.create_index(op.f('uq_directorio_metrica_codigo'), 'm_directorio_metrica', ['codigo'], unique=True)
    op.alter_column('m_directorio_metrica', 'descripcion',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m_directorio_metrica', 'codigo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('audit_log', 'user_agent')
    op.drop_column('audit_log', 'severity')
    op.drop_column('audit_log', 'event_category')
    # ### end Alembic commands ###
